version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install
    phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ecr.us-east-1 | docker login --username AWS --password-stdin 637423631641.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my/node-app .
      - docker tag my/node-app:latest 637423631641.dkr.ecr.us-east-1.amazonaws.com/my/node-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 637423631641.dkr.ecr.ecr.us-east-1.amazonaws.com/my/node-app:latest
 
artifacts:
  files:
    - '**/*'
